name: example
description: Example project for the "Explicit Content Extension".
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  file_picker: ^5.3.3
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.17+1
  uuid: ^3.0.7
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/adult-content-edit.png
